### ISSUE TITLE
Image is not display in Assignment 4

### ISSUE THREAD

**Issue by IlhamAhmadFahriji** [LugoBlogger/SI-251-4004-discrete-mathematics-1#1]
gambar di graf bipartite gak muncul pak display yang di assignment 4

![Screenshot (183)](https://github.com/LugoBlogger/SI-201-401-discrete-mathematics/assets/88475336/83126b5d-4a76-4f44-9185-92904539e94b)

**Comment by LugoBlogger** [comment]
I have updated the assignment-04. Please check it again.
